# Generated by Django 4.2 on 2023-04-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('ovulation_date', models.DateField(null=True)),
                ('flow_dates', models.DateField(null=True)),
                ('fertile_dates', models.DateField(null=True)),
                ('safe_periods', models.DateField(null=True)),
            ],
        ),
    ]
